### ISSUE TITLE
Deprecated OnActivityResult

### ISSUE THREAD

**Issue by pqasys** [dangiashish/GeoTagImage#1]
Are you planning to update code in view of the deprecated OnActivityResult. Please provide work around

**Comment by dangiashish** [comment]
> Are you planning to update code in view of the deprecated OnActivityResult. Please provide work around

Sure. I will work on it.

**Comment by dangiashish** [comment]
> Are you planning to update code in view of the deprecated OnActivityResult. Please provide work around

Hi @pqasys, I have updated the the deprecated onActivityResult.

https://github.com/dangiashish/GeoTagImage#handle-onactivityresult-method
